"""Production keyboard calibration artifacts and domain services."""

from .anchor_reference import (
    ANCHOR_REFERENCE_SCHEMA_VERSION,
    AnchorDefinition,
    AnchorReference,
    AnchorReferenceError,
    create_anchor_reference,
    load_anchor_reference,
    marker_key_ids_from_profile,
    save_anchor_reference,
)
from .artifacts import (
    KeyboardCalibrationArtifacts,
    load_keyboard_calibration_artifacts,
)
from .anchor_registration import (
    ANCHOR_REGISTRATION_SCHEMA_VERSION,
    AnchorRegistrationAccumulator,
)
from .contact_map import (
    CONTACT_MAP_SCHEMA_VERSION,
    COORDINATE_SYSTEM,
    DRAFT_SCHEMA_VERSION,
    INVENTORY_SCHEMA_VERSION,
    SAMPLES_PER_KEY,
    CalibrationDraft,
    ContactKey,
    ContactMapError,
    KeyCandidate,
    KeyboardContactMap,
    LayoutInventory,
    LayoutKey,
    RevisionMismatchError,
    build_contact_map,
    build_layout_inventory,
    load_calibration_draft,
    load_contact_map,
    nearest_sample_candidates,
    new_calibration_draft,
    save_calibration_draft,
    save_contact_map,
    updated_draft,
)
from .layout_profile import (
    LAYOUT_PROFILE_SCHEMA_VERSION,
    KeyboardKey,
    KeyboardLayoutProfile,
    LayoutProfileError,
    MarkerAssignment,
    load_layout_profile,
    save_layout_profile,
    validate_layout_profile,
)
from .session import CalibrationCapture, ContactCalibrationSession


__all__ = [
    "ANCHOR_REFERENCE_SCHEMA_VERSION",
    "ANCHOR_REGISTRATION_SCHEMA_VERSION",
    "CONTACT_MAP_SCHEMA_VERSION",
    "COORDINATE_SYSTEM",
    "DRAFT_SCHEMA_VERSION",
    "INVENTORY_SCHEMA_VERSION",
    "LAYOUT_PROFILE_SCHEMA_VERSION",
    "SAMPLES_PER_KEY",
    "AnchorDefinition",
    "AnchorReference",
    "AnchorReferenceError",
    "AnchorRegistrationAccumulator",
    "CalibrationCapture",
    "CalibrationDraft",
    "ContactCalibrationSession",
    "ContactKey",
    "ContactMapError",
    "KeyCandidate",
    "KeyboardCalibrationArtifacts",
    "KeyboardContactMap",
    "KeyboardKey",
    "KeyboardLayoutProfile",
    "LayoutInventory",
    "LayoutKey",
    "LayoutProfileError",
    "MarkerAssignment",
    "RevisionMismatchError",
    "build_contact_map",
    "build_layout_inventory",
    "create_anchor_reference",
    "load_anchor_reference",
    "load_calibration_draft",
    "load_contact_map",
    "load_keyboard_calibration_artifacts",
    "load_layout_profile",
    "marker_key_ids_from_profile",
    "nearest_sample_candidates",
    "new_calibration_draft",
    "save_anchor_reference",
    "save_calibration_draft",
    "save_contact_map",
    "save_layout_profile",
    "updated_draft",
    "validate_layout_profile",
]
